name: Run unit tests with PyTest and acceptance tests with Cypress
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Run unit test suite (PyTest)
        run: |
          pytest -v

      - name: Run acceptance test suite (Cypress)
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: flask run
          wait-on: "http://localhost:5001"
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          SECRET_KEY: SECRET_KEY